// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADYAHKjj_Nvy4eclJYG5wzD0uVZRojiY0',
    appId: '1:746528078481:web:a7418d21205fd748cedd30',
    messagingSenderId: '746528078481',
    projectId: 'feup-reuse',
    authDomain: 'feup-reuse.firebaseapp.com',
    storageBucket: 'feup-reuse.appspot.com',
    measurementId: 'G-5R5N843NJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0iqLg4evDqC2n67DAOrNog0PRaUCoY-M',
    appId: '1:746528078481:android:eaad65ef1ff64927cedd30',
    messagingSenderId: '746528078481',
    projectId: 'feup-reuse',
    storageBucket: 'feup-reuse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjydCgy9xZnKNVYU4BUiqZAd73Bv9u04',
    appId: '1:746528078481:ios:1c9ef3d9f587b56fcedd30',
    messagingSenderId: '746528078481',
    projectId: 'feup-reuse',
    storageBucket: 'feup-reuse.appspot.com',
    iosBundleId: 'com.example.feupReUse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjydCgy9xZnKNVYU4BUiqZAd73Bv9u04',
    appId: '1:746528078481:ios:981c8a8f2c1ce154cedd30',
    messagingSenderId: '746528078481',
    projectId: 'feup-reuse',
    storageBucket: 'feup-reuse.appspot.com',
    iosBundleId: 'com.example.feupReUse.RunnerTests',
  );
}
